config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'
  }


  # MEMO: devise_scope はあくまで devise が作るルーティングをカスタマイズするためのもののはず
  # つまり、独自のルーティングはこのブロックの中にある必要はない
  # また devise_for も内部で devise_scope を呼び出しているので、devise_scope のみでも良さそう
  devise_scope :user do
    get 'users/index', to: 'users/registrations#index'
    root 'home#index'
    get "/tutorial_top", :to => "home#tutorial_top"
    get "/tutorial_note", :to => "home#tutorial_note"
    get "/tutorial_note_index", :to => "home#tutorial_note_index"
    get "/tutorial_create_f_item", :to => "home#tutorial_create_f_item"
    get "/tutorial_index_f_item", :to => "home#tutorial_index_f_item"
    get "/tutorial_group_create", :to => "home#tutorial_group_create"
    get "/help", :to => "home#help"
    get "user/:id", :to => "users/registrations#detail"
    get "signup", :to => "users/registrations#new"
    get "login", :to => "users/sessions#new"
    get "logout", :to => "users/sessions#destroy"
    post "notes", :to => "notes#create"
    post "note", :to => "notes#destroy"
    post "count", :to => "notes#count"
    post "comment", :to => "comments#create"
    delete "comments/:id",:to => "comments#destroy"
    get "index",:to => "searches#index"
    post "favorite_items_destroy", :to => "favorite_items#destroy"

    resources :groups do
      collection do
        get :request_list
      end
      member do
        get :chatroom
        post :invite
        post :invite_reset
        post :join
      end
    end

    resources :favorite_items, only: [:index,:create,:new]  do
      collection do
        post :post
      end
    end

    resources :reviews
    
  end
end

app/models/favorite_item.rb
require "nkf"

class FavoriteItem < ApplicationRecord
  belongs_to :user
  belongs_to :group, optional: true
  validates :name, presence: true
end

app/controllers/favorite_items_controller.rb
class FavoriteItemsController < ApplicationController
    before_action :authenticate_user!
    before_action :correct_user, only: [:destroy]

    def index
      favorite_items = current_user.favorite_items.all
      @item_exists = favorite_items.present?
      @favorite_item_groups = current_user.favorite_item_groups
    end

    def new
      favorite_items = current_user.favorite_items.all
      @item_exists = favorite_items.present?
      @favorite_item_groups = current_user.favorite_item_groups

      @favorite_item = current_user.favorite_items.new
    end

    def create
      if params[:favorite_item][:name].present?
        params[:favorite_item][:name].split(/[[:blank:]]+/).each do |item|
          unless FavoriteItem.find_by(name: item,user_id: current_user.id).present?
            current_user.favorite_items.create(name: item)
          end
        end
        url = Rails.application.routes.recognize_path(request.referrer)
        if url == {:controller=>"home", :action=>"tutorial_create_f_item"}
          flash[:success] = "登録に成功しました！ページ下部のリンクから次のページへ進みましょう！"
          redirect_to tutorial_create_f_item_path
        else
          flash[:success] = "お気に入り商品を登録しました"
          redirect_to request.referrer || favorite_items_path
        end
      else
        flash[:danger] = "登録に失敗しました"
        redirect_to request.referrer || root_url
      end
    end

    def destroy
      params[:item][:id].each do |item_id|
        current_user.favorite_items.find_by(id: item_id).delete
      end
      flash[:warning] = "お気に入り商品を削除しました"
      redirect_to request.referrer || new_favorite_item_path
    end

    def post
      params[:item][:id].each do |item_id|
        item = current_user.favorite_items.find_by(id: item_id)
        note = Note.create(content: item.name, user_id: item.user_id, group_id: params[:group_id])
      end
        if params[:group_id].present?
          flash[:success] = "投稿しました"
          redirect_to chatroom_group_path(params[:group_id])
        else
          url = Rails.application.routes.recognize_path(request.referrer)
          if url == {:controller=>"home", :action=>"tutorial_index_f_item"}
            flash[:success] = "これでチュートリアルは終了！ページ下のボタンで移動し、アプリを使いはじめましょう！"
            redirect_to tutorial_note_index_path
          else
          flash[:success] = "投稿しました"
          redirect_to root_url
          end
        end
    end

    private

      def correct_user
        item = FavoriteItem.find(params[:item][:id]).first
        unless item.user_id == current_user.id
          flash[:danger] = "投稿者本人でないため削除出来ませんでした"
          redirect_to request.referrer || root_url
        end
      end
end

app/helpers/favorite_items_helper.rb
module FavoriteItemsHelper
end

app/views/favorite_items/index.html.erb
<p>お気に入り商品一覧</p>

<% if @item_exists %>

  <%= form_with url: post_favorite_items_path do |f| %>

    <% @favorite_item_groups.each do |key, items| %>
      <p>-<%= key %>-</p>
      <% items.each do |item| %>
        <%= check_box_tag 'item[id][]', item.id, checked = false, :id => "item_#{item.id}" %>
        <%= item.name %>
      <% end %><br/>
    <% end %>

      <ul class="f_item_link">
        <li><%= link_to "登録ページへ移動",new_favorite_item_path, class:"btn btn-dark favorite_back_btn" %></li>
        <li><%= link_to "戻る",:back , class:"btn btn-dark favorite_back_btn" %></li>
      </ul>

    <% if params[:group_id].present? %>

      <%= f.hidden_field :group_id, :value => params[:group_id] %>

    <% end %>

  <div class= "form_body" id="searches_form">
    <div class="form_title">投稿したい商品を選択し、投稿ボタンを押してください</div>

      <div class="f_item_form">
      <%= f.submit "投稿",class:"btn btn-primary" %>
      </div>
      <% end %>
  </div>

<% else %>

  <p>現在お気に入り商品はありません</p>
  <ul class="f_item_btn">
    <li><%= link_to "登録ページへ移動",new_favorite_item_path, class:"btn btn-dark" %></li>
    <li><%= link_to "戻る",:back , class:"btn btn-dark" %></li>
  </ul>
<% end %>

app/views/favorite_items/new.html.erb
<p>お気に入り商品登録</p>

<% if @item_exists %>

  <%= form_with url: favorite_items_destroy_path do |f| %>

    <% @favorite_item_groups.each do |key, items| %>
      <p>-<%= key %>-</p>
      <% items.each do |item| %>
        <%= check_box_tag 'item[id][]', item.id, checked = false, :id => "item_#{item.id}" %>
        <%= item.name %>
      <% end %><br/>
    <% end %>

    <div class="f_item_link"><%= link_to "戻る",:back , class:"btn btn-dark favorite_back_btn" %></div>

  　<%= f.submit "商品をまとめて削除",class:"btn btn-warning destroy" %>

  <% end %>

  <div class= "form_body" id="favorite_form">

      <div class="f_item_form">
        <p class="form_title">一覧に追加したい商品を入力してください</p>
        <%= form_with model: @favorite_item do |f| %>
          <%= f.text_field :name, class: "form-control", placeholder:'商品名を入力(複数ある場合は間に空白を入れて入力してください)' %>
          <%= f.submit "登録",class:"btn btn-primary" %>
        <% end %>
      </div>
  </div>

<% else %>

  <p>現在お気に入り商品はありません</p>
  <ul>
　<li><%= link_to "戻る",:back , class:"btn btn-dark" %></li>
  </ul>
  <div class= "form_body" id="favorite_form">
      <div class="f_item_form">
        <p class="form_title">一覧に追加したい商品を入力してください</p>
        <%= form_with model: @favorite_item do |f| %>
          <%= f.text_field :name, class: "form-control", placeholder:'商品名を入力(複数ある場合は間に空白を入れて入力してください)' %>
          <%= f.submit "登録",class:"btn btn-primary" %>
        <% end %>
      </div>
  </div>
<% end %>