config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'
  }


  # MEMO: devise_scope はあくまで devise が作るルーティングをカスタマイズするためのもののはず
  # つまり、独自のルーティングはこのブロックの中にある必要はない
  # また devise_for も内部で devise_scope を呼び出しているので、devise_scope のみでも良さそう
  devise_scope :user do
    get 'users/index', to: 'users/registrations#index'
    root 'home#index'
    get "/tutorial_top", :to => "home#tutorial_top"
    get "/tutorial_note", :to => "home#tutorial_note"
    get "/tutorial_note_index", :to => "home#tutorial_note_index"
    get "/tutorial_create_f_item", :to => "home#tutorial_create_f_item"
    get "/tutorial_index_f_item", :to => "home#tutorial_index_f_item"
    get "/tutorial_group_create", :to => "home#tutorial_group_create"
    get "/help", :to => "home#help"
    get "user/:id", :to => "users/registrations#detail"
    get "signup", :to => "users/registrations#new"
    get "login", :to => "users/sessions#new"
    get "logout", :to => "users/sessions#destroy"
    post "notes", :to => "notes#create"
    post "note", :to => "notes#destroy"
    post "count", :to => "notes#count"
    post "comment", :to => "comments#create"
    delete "comments/:id",:to => "comments#destroy"
    get "index",:to => "searches#index"
    post "favorite_items_destroy", :to => "favorite_items#destroy"

    resources :groups do
      collection do
        get :request_list
      end
      member do
        get :chatroom
        post :invite
        post :invite_reset
        post :join
      end
    end

    resources :favorite_items, only: [:index,:create,:new]  do
      collection do
        post :post
      end
    end

    resources :reviews
    
  end
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_members, dependent: :destroy
  has_many :users, through: :group_members
  has_many :notes, dependent: :destroy
  has_many :favorite_items, dependent: :destroy
  accepts_nested_attributes_for :group_members

  validates :name, presence: true
  validates :admin_user_id, presence: true
  validates :profile, length: { maximum: 100 }

  mount_uploader :image, ImageUploader
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!
  before_action :admin_user, only: [:edit,:update,:destroy]
  before_action :correct_user, only: [:join]
  # before_action :group_member


  def index
    # MEMO: ここで params とってきているけど意味はない
    @groups = current_user.groups.where(params[:id])
  end

  def new
    @group = current_user.own_groups.new
  end

  def create
    # MEMO: 複数のリソースを同時に操作しているのでトランザクションが必要
    ActiveRecord::Base.transaction do
      @group = current_user.own_groups.new(group_params)
      @group.save!

      group_member = @group.group_members.build(user_id: current_user.id, activated: true)
      group_member.save!
    end
    url = Rails.application.routes.recognize_path(request.referrer)
    if url == {:controller=>"home", :action=>"tutorial_group_create"}
      flash[:success] = "登録に成功しました！ページ下にて招待したいユーザーを検索して招待しましょう！"
    else
      flash[:success]= "グループを作成しました"
    end
    redirect_to group_path(@group)
  rescue => e
    flash[:danger]= "グループ作成に失敗しました。再度やり直してください"
    render 'groups/new'
# MEMO: 全角スペースが紛れ込んでいる。エディタで全角文字を可視化する設定をした方が良い
# 　　 end
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])
    if @group.update(group_params)
      redirect_to group_path(@group)
    else
      render 'groups/edit'
    end
  end

  def destroy
    binding.pry
    Group.find(params[:id]).destroy
    flash[:success] = "グループを削除しました"
    redirect_to root_path
  end

  def invite
    if params[:id].to_i != current_user.id
    @group = Group.find(params[:group_id])
    @member = @group.group_members.create(user_id: params[:id])
    flash[:success] = "#{@member.user.name}さんを招待しました"
    redirect_to request.referrer || root_url
    else
      flash[:danger] = "無効な処理です。自分以外のユーザーへリクエストしてください"
      redirect_to request.referrer || root_url
    end
  end

  def invite_reset
    @group = Group.find(params[:group_id])
    @group.group_members.find_by(user_id: params[:id]).destroy
    redirect_to request.referrer || root_url
  end

  def join
      @group = Group.find(params[:id])
      @group.group_members.find_by(user_id: params[:user_id]).update(activated:true)
      flash[:success] = "グループに参加しました"
      redirect_to chatroom_group_path
  end

  def show
    @group = Group.find(params[:id])
    @members = @group.group_members.where(activated: true)
  end

  def chatroom
    @group = Group.find(params[:id])
    @notes = Note.find_by(id: params[:id])
    # MEMO: N+1 になっているので :comments も includes させる
    @group_notes = Note.includes([:user]).where(group_id: @group.id)
    @members = @group.users.select(:name)
  end

  def request_list
  end

  private

    def correct_user
      # MEMO: おそらくまだ実装中だと思うが、リクエストしているユーザの情報を使う場合は params 自体が必要なく、盲目的に current_user を使う方が良い
      unless params[:user_id].to_i == current_user.id
        flash[:danger] = "本人でないためグループリクエストの承認が出来ません"
        redirect_to request.referrer || root_url
      end
    end

    def admin_user
      # MEMO: user モデルのメソッドで管理者かどうかをチェックするメソッドを作った方が良い
      group = current_user.groups.find(params[:id])
      unless group.admin_user_id == current_user.id
        flash[:danger] = "管理者権限がないため実行出来ません"
        render 'home/index'
      end
    end

    # def group_member
    #   member = group_members.where(activated: true)
    #
    #   # unless group.
    # end

    def group_params
      params.require(:group).permit(:name, :profile, :image)
    end

    def join_params
      params.permit(:user_id)
    end

end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/chatroom.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-12">
      <div class="row">

        <div class="col-12 d-block d-md-none promotion_sm">
          <p>広告スペース(小)</p>
        </div>
        <div class="col-md-2 d-none d-md-block promotion_bg">
          <p>広告スペース(大)</p>
        </div>

        <div class="col-md-8 chatroom_info">
　　　　　  <div class="row info group_title">
            <div class="col-12">
          <%= "ルーム名：#{@group.name}" %>
            <% if @group.image.present? %>
              <img src= "<%= @group.image %>" class="image_icon">
            <% else %>
              <img src= "/assets/default_group_icon.png" class="image_icon">
            <% end %><br/>
            </div>
          </div>

            <%= form_with url: note_path do |f| %>
              <% if @group_notes.present? %>
                <% @group_notes.each do |note| %>


                  <ul class="row info">

                  <% unless note.user.name == current_user.name %>
                    <li class="col-6 namespace_left">
                      <%= note.user.name %>
                      <% if note.user.image.present? %>
                        <img src="<%= note.user.image %>" class="user_icon" >
                      <% else %>
                        <img src="/assets/default_user_icon.jpg" class="user_icon" >
                      <% end %>
                    </li>
                  <% else %>
                  <li class="col-6"></li>
                  <% end %>
                  <% if note.user.name == current_user.name %>
                    <li class="col-6">
                      <%= note.user.name %>
                      <% if note.user.image.present? %>
                        <img src="<%= note.user.image %>" class="user_icon" >
                      <% else %>
                        <img src="/assets/default_user_icon.jpg" class="user_icon" >
                      <% end %>
                    </li>
                  <% else %>
                    <li class="col-6 namespace_right"></li>
                  <% end %>
                  </ul>


                <div class="time"><%= note.created_at.to_s(:datetime) %></div>

                  <%= check_box_tag 'note[id][]', note.id, checked = false, :id => "note_id" %>

                  <div class="btn btn-dark">
                    <ul>
                      <li>
                        <div class="note_body">
                          <div class="note_content">
                            <%= note.content %>
                            <% if note.image.present? %>
                              <img src="<%= note.image %>" class="note_image" >
                            <% end %>
                            <%= note.count %>
                              <% if note.count.present? %>
                                <span>個</span>
                              <% end %>
                          </div>


                        </div>
                      </li>
                      <li><button type="button" class="btn btn-secondary js_count_btn" data-toggle="modal" data-target="#count_Modal" value="<%= note.id %>" id="js_count"><i class="fa fa-sort" aria-hidden="true"></i></button></li>
                      <li><button type="button" class="btn btn-secondary js_comment_btn" data-toggle="modal" data-target="#comment_Modal" value="<%= note.id %>" id="js_comment"><i class="fa fa-pencil" aria-hidden="true"></i></button></li>
                    </ul>
                    <div class="comment">
                      <% note.comments.each do |comment| %>
                        <div class="comment_list">
                          <%= link_to comment.content ,"/comments/#{comment.id}", method: :delete,data:{confirm: "本当に削除しますか?"} %>
                            <span> : </span>
                          <%= comment.user.name %>
                        </div>
                      <% end %>
                    </div>
                  </div>


                <% end %>

              <% else %>

                <p>現在買うものはありません</p>

              <% end %>

          <div class = "destroy">
            <%= f.submit '購入しました', class: 'btn btn-warning' %>
          </div>
        </div>
        <% end %>

        <div class="col-md-2 d-none d-md-block promotion_bg">
          <p>広告スペース(大)</p>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- 数量入力用モーダル -->
<div class="modal fade" id="count_Modal" tabindex="-1" role="dialog" aria-labelledby="count_ModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <%= form_with url: count_path do |f| %>
        <h4 class="modal-title" id="comment_ModalLabel">数量入力欄</h4>
          <div class="modal-body">
            <%= hidden_field_tag :note_id, "", {id: "count_id"} %>
            <%= f.select :count, [['1', 1], ['2', 2], ['3', 3], ['4', 4], ['5', 5], ['6', 6], ['7', 7], ['8', 8], ['9', 9], ['10', 10]],
                { include_blank: true, selected: 1 }, { id: "user_id", class: "user_class" } %>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-dark" data-dismiss="modal">戻る</button>
            <%= f.submit "投稿する", class: "btn btn-primary" %>
          </div>
      <% end %>
    </div>
  </div>
</div>

<!-- コメント入力用モーダル -->
<div class="modal fade" id="comment_Modal" tabindex="-1" role="dialog" aria-labelledby="comment_ModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <%= form_with url: comment_path do |f| %>
        <h4 class="modal-title" id="comment_ModalLabel">コメント入力欄</h4>
        <div class="modal-body">
          <%= hidden_field_tag :note_id, "", {id: "comment_id"} %>
          <%= f.text_area :content, size: "10x5", class: "form-control" %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-dark" data-dismiss="modal">戻る</button>
          <%= f.submit "投稿する", class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

  <div class="forms">
    <%= form_with url: notes_path do |f| %>
      <div class="form_body">
        <%= f.hidden_field :group_id, :value => @group.id %>
        <%= f.text_field :content,class:'form form-control' , placeholder: "商品名を入力(複数ある場合は間に空白を入れて入力してください)" %>　
        <div class="note_form_contents">　　　
          <%= f.label :image, class:'image_form' do %>
          <label>
            <i class="fa fa-image btn btn-dark "></i>
            <%= f.file_field :image, class: "file_field" %>
          </label>
          <% end %>
          <%= link_to favorite_items_path(group_id: @group.id), class:"btn btn-dark" do %>
          <i class="fa fa-star" aria-hidden="true"></i>
          <% end %>
          <%= f.submit "投稿", class: "btn btn-primary form-btn " %>
        </div>
      </div>
    <% end %>
  </div>


<script type="text/javascript">
  $('.js_count_btn').click(function() {
  $('#count_id').val(this.value);
  });
  $('.js_comment_btn').on('click', function () {
  $('#comment_id').val(this.value);
  })
</script>

app/views/groups/edit.html.erb
<p>グループ情報編集</p>

<p>下記項目を入力してグループ情報変更ボタンを押してください</p>

<div class="group_form">

  <%= form_with model: @group do |f| %>

    <div>
      <%= f.label :"名前" %>
      <%= f.text_field :name, class:'form-control' %>
    </div>

    <div>
      <%= f.label :"グループプロフィール" %>
      <%= f.text_area :profile, class:'form-control' %><br />
    </div>

    <div class="custom_file_title">アイコン画像</div>
    <div class="custom-file">
      <%= f.file_field :image, class: "custom-file-input" ,id: "customFile" %>
      <label class="custom-file-label" for="customFile">タップして画像を選択</label>
    </div>

    <div>
      <br /><%= f.submit "グループ情報変更", class:"btn btn-primary" %>
    </div>
  <% end %>

<button class="btn btn-warning"><%= link_to "削除", group_path(@group.id), method: :delete,data:{confirm: "本当に削除しますか?"} %></button>

</div>

<script type="text/javascript">
$('.custom-file-input').on('change',function(){
  $(this).next('.custom-file-label').html($(this)[0].files[0].name);
})
</script>

app/views/groups/index.html.erb
<% if @groups.present? %>

<p>所属グループ一覧</p>

  <% @groups.each do |group| %>
  　<ul class="group_info">
    <% if group.image.present? %>
      <li class="group_name"><img src= "<%= group.image %>" class="image_icon">
    <% else %>
      <li class="group_name"><img src= "/assets/default_group_icon.png" class="image_icon">
    <% end %>
      <%= link_to group.name,group_path(group.id) %></li>
      <li class="index_group_profile"><%= group.profile %></li>
    </ul>
  <% end %>

<% else %>

  <p>現在所属しているグループはありません</p>

<% end %>

app/views/groups/new.html.erb
<p>グループ作成</p>

<p>下記項目を入力してグループ登録完了ボタンを押してください</p>

<div class="group_form">

  <%= form_with model: @group do |f| %>

    <div>
      <%= f.label :"名前" %><i>(必須)</i>
      <%= f.text_field :name, class:'form-control',placeholder: "例:○○家のおつかいリスト" %>
    </div>

    <div>
      <%= f.label :"グループプロフィール" %>
      <%= f.text_area :profile, class:'form-control',placeholder: "例:美味しく安く生活！おやつは300円まで！笑" %><br />
    </div>

    <div>
      <br /><%= f.submit "グループ登録完了", class:"btn btn-primary" %>
    </div>
  <% end %>

</div>

app/views/groups/request_list.html.erb
<% if @request.present? %>

  <% @request.each do |request| %>
    <ul>
      <% if request.group.image.present? %>
        <li><img src= "<%= request.group.image %>" class="image_icon"></li>
      <% else %>
        <li><img src= "/assets/default_group_icon.png" class="image_icon"></li>
      <% end %>
        <li><%= request.group.name %></li>
        <li>
          <%= form_with url:join_group_path(request.group_id) do |f| %>
            <%= f.hidden_field :user_id, :value => current_user.id %>
            <%= f.submit "グループに入る",class: "btn btn-primary" %>
          <% end %>
        </li>
    </ul>
  <% end %>
<% else %>

 <p>現在グループリクエストはありません</p>

<% end %>

app/views/groups/show.html.erb
<ul class="group_info">
  <li><h2>グループ名:<%= @group.name %></h2></li>
  <% if @group.image.present? %>
    <li><img src= "<%= @group.image %>" class="image_icon"></li>
  <% else %>
    <li><img src= "/assets/default_group_icon.png" class="_show_group_icon"></li>
  <% end %>
</ul>

<p>所属メンバー名</p>
  <% @members.each do |member| %>
    <ul>
      <li><%= member.user.name %></li>
      <% if member.user.image.present? %>
        <li><img src= "<%= member.user.image %>" class="image_icon"></li>
      <% else %>
        <li><img src= "/assets/default_user_icon.jpg" class="image_icon"></li>
      <% end %>
    </ul>
  <% end %>

<p>グループプロフィール</p>
  <div class="group_profile">
    <%= @group.profile %>
  </div>

<p><%= link_to "グループ情報編集",edit_group_path(@group.id) %></p>

<div class="form_body" id="searches_form">
  <div class="form_title">招待したいユーザーを検索</div>

  <%= form_with url: index_path, method: :get, local: true do |f| %>
      <%= f.hidden_field :group_id, :value => @group.id %>
      <%= f.text_field :name,class:'form-control search_form', placeholder: "ユーザー名を入力" %>
      <%= f.submit "検索", class: "btn btn-light" %>
  <% end %>
</div>