config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'
  }


  # MEMO: devise_scope はあくまで devise が作るルーティングをカスタマイズするためのもののはず
  # つまり、独自のルーティングはこのブロックの中にある必要はない
  # また devise_for も内部で devise_scope を呼び出しているので、devise_scope のみでも良さそう
  devise_scope :user do
    get 'users/index', to: 'users/registrations#index'
    root 'home#index'
    get "/tutorial_top", :to => "home#tutorial_top"
    get "/tutorial_note", :to => "home#tutorial_note"
    get "/tutorial_note_index", :to => "home#tutorial_note_index"
    get "/tutorial_create_f_item", :to => "home#tutorial_create_f_item"
    get "/tutorial_index_f_item", :to => "home#tutorial_index_f_item"
    get "/tutorial_group_create", :to => "home#tutorial_group_create"
    get "/help", :to => "home#help"
    get "user/:id", :to => "users/registrations#detail"
    get "signup", :to => "users/registrations#new"
    get "login", :to => "users/sessions#new"
    get "logout", :to => "users/sessions#destroy"
    post "notes", :to => "notes#create"
    post "note", :to => "notes#destroy"
    post "count", :to => "notes#count"
    post "comment", :to => "comments#create"
    delete "comments/:id",:to => "comments#destroy"
    get "index",:to => "searches#index"
    post "favorite_items_destroy", :to => "favorite_items#destroy"

    resources :groups do
      collection do
        get :request_list
      end
      member do
        get :chatroom
        post :invite
        post :invite_reset
        post :join
      end
    end

    resources :favorite_items, only: [:index,:create,:new]  do
      collection do
        post :post
      end
    end

    resources :reviews
    
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    if current_user.present?
      @own_notes = current_user.notes.includes(:comments).all
    else
      @own_notes = []
    end
  end

  # MEMO: Rails の controller には標準の CRUD アクション以外は作らない方がシンプルに保てる
  def help
  end

  def tutorial_top
  end

  def tutorial_note_index
    if current_user.present?
      # MEMO: all は必要ない
      @own_notes = current_user.notes.all
    else
      @own_notes = []
    end
  end

  def tutorial_note
    if current_user.notes.present?
      @own_notes = current_user.notes.all
    else
      @own_notes = []
    end
  end

  def tutorial_create_f_item
    @favorite_item = current_user.favorite_items.new
    @favorite_items = current_user.favorite_items.all
    @A_line = []
    @K_line = []
    @S_line = []
    @T_line = []
    @N_line = []
    @H_line = []
    @M_line = []
    @Y_line = []
    @R_line = []
    @W_line = []
    @other_line = []

      @favorite_items.each do |item|
        i_initial = NKF.nkf("-h1 -w",item.name[0]).tr("A-Z0-9","Ａ-Ｚ０-９")
          if ["あ","い","う","え","お","a","i","u","e","o","A","I","U","E","O"].include?(i_initial)
            @A_line << item
          elsif ["か","き","く","け","こ","が","ぎ","ぐ","げ","ご","c","k","q","C","K","Q"].include?(i_initial)
            @K_line << item
          elsif ["さ","し","す","せ","そ","ざ","じ","ず","ぜ","ぞ","s","z","S","Z"].include?(i_initial)
            @S_line << item
          elsif ["た","ち","つ","て","と","だ","ぢ","づ","で","ど","t","d","T","D"].include?(i_initial)
            @T_line << item
          elsif ["な","に","ぬ","ね","の","n","N"].include?(i_initial)
            @N_line << item
          elsif ["は","ひ","ふ","へ","ほ","ば","び","ぶ","べ","ぼ","h","b","H","B"].include?(i_initial)
            @H_line << item
          elsif ["ま","み","む","め","も","m","M"].include?(i_initial)
            @M_line << item
          elsif ["や","ゆ","よ","y","Y"].include?(i_initial)
            @Y_line << item
          elsif ["ら","り","る","れ","ろ","l","r","L","R"].include?(i_initial)
            @R_line << item
          elsif ["わ","を","ん"].include?(i_initial)
            @W_line << item
          else
            @other_line << item
          end
      end
  end

  def tutorial_index_f_item
    @favorite_items = current_user.favorite_items.all
    @A_line = []
    @K_line = []
    @S_line = []
    @T_line = []
    @N_line = []
    @H_line = []
    @M_line = []
    @Y_line = []
    @R_line = []
    @W_line = []
    @other_line = []

      @favorite_items.each do |item|
        i_initial = NKF.nkf("-h1 -w",item.name[0]).tr("A-Z0-9","Ａ-Ｚ０-９")
          if ["あ","い","う","え","お","a","i","u","e","o","A","I","U","E","O"].include?(i_initial)
            @A_line << item
          elsif ["か","き","く","け","こ","が","ぎ","ぐ","げ","ご","c","k","q","C","K","Q"].include?(i_initial)
            @K_line << item
          elsif ["さ","し","す","せ","そ","ざ","じ","ず","ぜ","ぞ","s","z","S","Z"].include?(i_initial)
            @S_line << item
          elsif ["た","ち","つ","て","と","だ","ぢ","づ","で","ど","t","d","T","D"].include?(i_initial)
            @T_line << item
          elsif ["な","に","ぬ","ね","の","n","N"].include?(i_initial)
            @N_line << item
          elsif ["は","ひ","ふ","へ","ほ","ば","び","ぶ","べ","ぼ","h","b","H","B"].include?(i_initial)
            @H_line << item
          elsif ["ま","み","む","め","も","m","M"].include?(i_initial)
            @M_line << item
          elsif ["や","ゆ","よ","y","Y"].include?(i_initial)
            @Y_line << item
          elsif ["ら","り","る","れ","ろ","l","r","L","R"].include?(i_initial)
            @R_line << item
          elsif ["わ","を","ん"].include?(i_initial)
            @W_line << item
          else
            @other_line << item
          end
      end
  end

  def tutorial_group_SearchUser
    @group = Group.find(params[:id])
    @members = @group.group_members.where(activated: true)
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/help.html.erb
<h4>利用手順一覧</h4><br />

  <div class="help_Link"><%= link_to "1.買い物メモの投稿",tutorial_note_path %></div>
  <div class="help_Link"><%= link_to "2.お気に入り商品の登録",tutorial_create_f_item_path  %></div>
  <div class="help_Link"><%= link_to "3.お気に入り商品の投稿",tutorial_index_f_item_path %></div>
  <div class="help_Link"><%= link_to "4.グループの作成/ユーザー招待" ,tutorial_group_create_path %></div>

app/views/home/index.html.erb
<!-- MEMO: サインイン前とサインイン後の view ファイルを分けた方が見通しが良さそう -->
<%if user_signed_in? %>

  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12">
        <div class="row">

          <div class="col-12 d-block d-md-none promotion_sm">
            <p>広告スペース(小)</p>
          </div>
          <div class="col-md-2 d-none d-md-block promotion_bg">
            <p>広告スペース(大)</p>
          </div>

          <div class="col-md-8 chatroom_info">
            <!-- MEMO: ここの分岐もパーシャルにした方が良い -->
          <%= form_with url: note_path do |f| %>

            <% if @own_notes.present? %>

              <% @own_notes.each do |note| %>

                <%= check_box_tag 'note[id][]', note.id, checked = false, :id => "note_#{note.id} " %>

                <div class="btn btn-dark note">
                  <ul>
                    <li>
                      <div class="note_body">
                        <div class="note_content">
                          <%= note.content %>
                          <% if note.image.present? %>
                            <img src="<%= note.image %>"class="note_image" >
                          <% end %>
                          <%= note.count %>
                            <% if note.count.present? %>
                              <span>個</span>
                            <% end %>
                        </div>


                      </div>
                    </li>
                    <li><button type="button" class="btn btn-secondary js_count_btn" data-toggle="modal" data-target="#count_Modal" value="<%= note.id %>" id="js_count"><i class="fa fa-sort" aria-hidden="true"></i></button></li>
                    <li><button type="button" class="btn btn-secondary js_comment_btn" data-toggle="modal" data-target="#comment_Modal" value="<%= note.id %>" id="js_comment"><i class="fa fa-pencil" aria-hidden="true"></i></button></li>
                  </ul>
                  <div class="comment">
                    <% note.comments.each do |comment| %>
                      <div class="comment_list">
                        <%= link_to comment.content ,"/comments/#{comment.id}", method: :delete,data:{confirm: "本当に削除しますか?"} %>
                          <span> : </span>
                        <%= comment.user.name %>
                      </div>
                    <% end %>
                  </div>
                </div>
          <div class="time"><%= note.created_at.to_s(:datetime) %></div>
              <% end %>

              <%= f.submit '購入しました', class: 'btn btn btn-warning destroy' %>

            <% else %>

              <p>現在買うものはありません</p>

            <% end %>
          </div>
          <% end %>
          <div class="col-md-2 d-none d-md-block promotion_bg">
            <p>広告スペース(大)</p>
          </div>
          </div>
        </div>
      </div>
    </div>
  </div>


      <!-- 数量入力用モーダル -->
      <div class="modal fade" id="count_Modal" tabindex="-1" role="dialog" aria-labelledby="count_ModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <%= form_with url: count_path do |f| %>
              <h4 class="modal-title" id="comment_ModalLabel">数量入力欄</h4>
                <div class="modal-body">
                  <%= hidden_field_tag :note_id, "", {id: "count_id"} %>
                  <%= f.select :count, [['1', 1], ['2', 2], ['3', 3], ['4', 4], ['5', 5], ['6', 6], ['7', 7], ['8', 8], ['9', 9], ['10', 10]],
                      { include_blank: true, selected: 1 }, { id: "user_id", class: "user_class" } %>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-dark" data-dismiss="modal">戻る</button>
                  <%= f.submit "投稿する", class: "btn btn-primary" %>
                </div>
            <% end %>
          </div>
        </div>
      </div>

      <!-- コメント入力用モーダル -->
      <div class="modal fade" id="comment_Modal" tabindex="-1" role="dialog" aria-labelledby="comment_ModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <%= form_with url: comment_path do |f| %>
              <h4 class="modal-title" id="comment_ModalLabel">コメント入力欄</h4>
              <div class="modal-body">
                <%= hidden_field_tag :note_id, "", {id: "comment_id"} %>
                <%= f.text_area :content, size: "10x5", class: "form-control" %>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-dark" data-dismiss="modal">戻る</button>
                <%= f.submit "投稿する", class: "btn btn-primary" %>
              </div>
            <% end %>
          </div>
        </div>
      </div>

  <div class="form_body">
    <%= form_with url: notes_path do |f| %>

        <%= f.text_field :content,class:'form form-control' , placeholder: "商品名を入力(複数ある場合は間に空白を入れて入力してください)" %>　
        <div class="note_form_contents">　　　
        <%= f.label :image, class:'image_form' do %>
        <label>
          <i class="fa fa-image btn btn-dark "></i>
          <%= f.file_field :image, class: "file_field" %>
        </label>
        <% end %>
        <%= link_to favorite_items_path, class:"btn btn-dark" do %>
        <i class="fa fa-star" aria-hidden="true"></i>
        <% end %>
        <%= f.submit "投稿", class: "btn btn-primary form-btn " %>
      </div>
    <% end %>
  </div>

  <script type="text/javascript">
    // MEMO: Bootstarap はモーダルを開いた時のコールバックが設定できるのでこっちのが良い
    // $('#count_Modal').on('show.bs.modal', function(event) {
    //   console.log('open modal');
    //   console.log(event.relatedTarget);
    // });
  $('.js_count_btn').click(function() {
  $('#count_id').val(this.value);
  });
  $('.js_comment_btn').on('click', function () {
  $('#comment_id').val(this.value);
  })
  </script>

<% else %>

  <h1 class="app_title">
    有吉の買い物メモ<br>アプリへようこそ
  </h1>

<h3><a <%= link_to "ユーザー登録して利用開始！",signup_path %></a></h3><br />
<h5><a <%= link_to "登録済みの方はコチラから",new_user_session_path %></a></h5>

<% end %>

app/views/home/tutorial_create_f_item.html.erb
<% if @favorite_items.present? %>
 <div class="alert alert-dark">
  <small>
    買い物メモの投稿と同様、チェックを入れて[商品をまとめて削除]ボタンを押すことで、削除することが出来ます♪<br>
  </small>
</div>

  <%= form_with url: favorite_items_destroy_path do |f| %>


  　<p>-あ行-</p>
      <% @A_line.each do |item| %>
        <%= check_box_tag 'item[id][]', item.id, checked = false, :id => "item_#{item.id}" %>
        <%= item.name %>
      <% end %><br/>

  　<p>-か行-</p>
      <% @K_line.each do |item| %>
        <%= check_box_tag 'item[id][]', item.id, checked = false, :id => "item_#{item.id}" %>
        <%= item.name %>
      <% end %><br/>

  　<p>-さ行-</p>
      <% @S_line.each do |item| %>
        <%= check_box_tag 'item[id][]', item.id, checked = false, :id => "item_#{item.id}" %>
        <%= item.name %>
      <% end %><br/>

  　<p>-た行-</p>
      <% @T_line.each do |item| %>
        <%= check_box_tag 'item[id][]', item.id, checked = false, :id => "item_#{item.id}" %>
        <%= item.name %>
      <% end %><br/>

  　<p>-な行-</p>
      <% @N_line.each do |item| %>
        <%= check_box_tag 'item[id][]', item.id, checked = false, :id => "item_#{item.id}" %>
        <%= item.name %>
      <% end %><br/>

  　<p>-は行-</p>
      <% @H_line.each do |item| %>
        <%= check_box_tag 'item[id][]', item.id, checked = false, :id => "item_#{item.id}" %>
        <%= item.name %>
      <% end %><br/>

  　<p>-ま行-</p>
      <% @M_line.each do |item| %>
        <%= check_box_tag 'item[id][]', item.id, checked = false, :id => "item_#{item.id}" %>
        <%= item.name %>
      <% end %><br/>

  　<p>-や行-</p>
      <% @Y_line.each do |item| %>
        <%= check_box_tag 'item[id][]', item.id, checked = false, :id => "item_#{item.id}" %>
        <%= item.name %>
      <% end %><br/>

  　<p>-ら行-</p>
      <% @R_line.each do |item| %>
        <%= check_box_tag 'item[id][]', item.id, checked = false, :id => "item_#{item.id}" %>
        <%= item.name %>
      <% end %><br/>

  　<p>-わ行-</p>
      <% @W_line.each do |item| %>
        <%= check_box_tag 'item[id][]', item.id, checked = false, :id => "item_#{item.id}" %>
        <%= item.name %>
      <% end %><br/>

  　<p>-その他-</p>
      <% @other_line.each do |item| %>
        <%= check_box_tag 'item[id][]', item.id, checked = false, :id => "item_#{item.id}" %>
        <%= item.name %><br />
      <% end %>

      <ul>
        <li><%= link_to "1つ前に戻る",tutorial_note_path, class:"btn btn-dark" %></li>
        <li><%= link_to "次の項目に進む",tutorial_index_f_item_path, class:"btn btn-warning" %></li>
        <li><%= link_to "チュートリアルを終了",root_path, class:"btn btn-dark" %></li>
      </ul>

　  <%= f.submit "商品をまとめて削除",class:"btn btn-warning destroy" %>

  <% end %>

  <div class= "form_body" id="favorite_form">

      <div class="f_item_form">
        <p class="form_title">一覧に追加したい商品を入力してください</p>
        <%= form_with model: @favorite_item do |f| %>
          <%= f.text_field :name, class: "form-control", placeholder:'商品名を入力(複数ある場合は間に空白を入れて入力してください)' %>
          <%= f.submit "登録",class:"btn btn-primary" %>
        <% end %>
      </div>
  </div>
<% else %>
  <div class="alert alert-success">お気に入り商品を登録してみましょう！ページ下の入力フォームに入力し、[登録]ボタンを押してください</div>

  <p>日頃よく買う商品を『お気に入り商品』として登録することで、投稿をスムーズに行うことが出来ます！<br/>是非一度試してみましょう♪</p>

  <ul>
    <li><%= link_to "1つ前に戻る",tutorial_note_path, class:"btn btn-dark" %></li>
    <li><%= link_to "チュートリアルを終了",root_path, class:"btn btn-dark" %></li>
  </ul>

  <div class= "form_body" id="favorite_form">
    <div class="f_item_form">
      <p class="form_title">一覧に追加したい商品を入力してください</p>
      <%= form_with model: @favorite_item do |f| %>
        <%= f.text_field :name, class: "form-control", placeholder:'商品名を入力(複数ある場合は間に空白を入れて入力してください)' %>
        <%= f.submit "登録",class:"btn btn-primary" %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/home/tutorial_note.html.erb
<% if @own_notes.present? %>
 <div class="alert alert-dark">
  <small>
    1.投稿の削除は、消したい投稿にチェックを入れて、画面下に表示される[購入しました]ボタンを押してください！<br>
    2.投稿には数量やコメントをつけることも出来ます！右側のアイコンをタップして試してみましょう♪<br/>
    (コメントは、削除したいものをタップすることで削除することが出来ます)<br/>
    3.画像投稿を行うことも可能です！投稿フォーム下のアイコンをタップして試してみましょう♪
  </small>
</div>
<p>思う存分触って満足したら次のページへ！</p>
<% end %>
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12">
        <div class="row">

          <div class="col-md-2">
          </div>

          <div class="col-md-8 chatroom_info">
          <%= form_with url: note_path do |f| %>

            <% if @own_notes.present? %>

              <% @own_notes.each do |note| %>

                <%= check_box_tag 'note[id][]', note.id, checked = false, :id => "note_#{note.id} " %>

                <div class="btn btn-dark">
                  <ul>
                    <li>
                      <div class="note_body">
                        <div class="note_content">
                          <%= note.content %>
                          <% if note.image.present? %>
                            <img src="<%= note.image %>" class="note_image" >
                          <% end %>
                          <%= note.count %>
                            <% if note.count.present? %>
                              <span>個</span>
                            <% end %>
                        </div>


                      </div>
                    </li>
                    <li><button type="button" class="btn btn-secondary js_count_btn" data-toggle="modal" data-target="#count_Modal" value="<%= note.id %>" id="js_count"><i class="fa fa-sort" aria-hidden="true"></i></button></li>
                    <li><button type="button" class="btn btn-secondary js_comment_btn" data-toggle="modal" data-target="#comment_Modal" value="<%= note.id %>" id="js_comment"><i class="fa fa-pencil" aria-hidden="true"></i></button></li>
                  </ul>
                  <div class="comment">
                    <% note.comments.each do |comment| %>
                      <div class="comment_list">
                        <%= link_to comment.content ,"/comments/#{comment.id}", method: :delete,data:{confirm: "本当に削除しますか?"} %>
                          <span> : </span>
                        <%= comment.user.name %>
                      </div>
                    <% end %>
                  </div>
                </div>

                <div class="time"><%= note.created_at.to_s(:datetime) %></div>

              <% end %>

                <%= f.submit '購入しました', class: 'btn btn btn-warning destroy' %>

          <% else %>
            <div class="alert alert-success">まずはメモの投稿！ページ下の入力フォームに商品名を入力して[投稿]ボタンを押してください</div>

          <% end %>

        <ul>
          <li><%= link_to "お気に入り商品 の説明に進む",tutorial_create_f_item_path, class:"btn btn-warning" %></li>
          <li><%= link_to "チュートリアルを終了",root_path, class:"btn btn-dark" %></li>
        </ul>

        </div>

        <div class="col-md-2">
        </div>



      </div>
    </div>
  </div>

        <% end %>

      <!-- 数量入力用モーダル -->
      <div class="modal fade" id="count_Modal" tabindex="-1" role="dialog" aria-labelledby="count_ModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <%= form_with url: count_path do |f| %>
              <h4 class="modal-title" id="comment_ModalLabel">数量入力欄</h4>
                <div class="modal-body">
                  <%= hidden_field_tag :note_id, "", {id: "count_id"} %>
                  <%= f.select :count, [['1', 1], ['2', 2], ['3', 3], ['4', 4], ['5', 5], ['6', 6], ['7', 7], ['8', 8], ['9', 9], ['10', 10]],
                      { include_blank: true, selected: 1 }, { id: "user_id", class: "user_class" } %>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-default" data-dismiss="modal">戻る</button>
                  <%= f.submit "投稿する", class: "btn btn-primary" %>
                </div>
            <% end %>
          </div>
        </div>
      </div>

      <!-- コメント入力用モーダル -->
      <div class="modal fade" id="comment_Modal" tabindex="-1" role="dialog" aria-labelledby="comment_ModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <%= form_with url: comment_path do |f| %>
              <h4 class="modal-title" id="comment_ModalLabel">コメント入力欄</h4>
              <div class="modal-body">
                <%= hidden_field_tag :note_id, "", {id: "comment_id"} %>
                <%= f.text_area :content, size: "10x5", class: "form-control" %>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">戻る</button>
                <%= f.submit "投稿する", class: "btn btn-primary" %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
  </div>
  <div class="form_body">
    <%= form_with url: notes_path do |f| %>

        <%= f.text_field :content,class:'form form-control' , placeholder: "商品名を入力(複数ある場合は間に空白を入れて入力してください)" %>　
        <div class="note_form_contents">　　　
        <%= f.label :image, class:'image_form' do %>
        <label>
          <i class="fa fa-image btn btn-dark "></i>
          <%= f.file_field :image, class: "file_field" %>
        </label>
        <% end %>
        <%= f.submit "投稿", class: "btn btn-primary form-btn " %>
      </div>
    <% end %>
  </div>

  <script type="text/javascript">
  $('.js_count_btn').click(function() {
  $('#count_id').val(this.value);
  });
  $('.js_comment_btn').on('click', function () {
  $('#comment_id').val(this.value);
  })
  </script>

app/views/home/tutorial_note_index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-12">
      <div class="row">

        <div class="col-md-2">
        </div>

        <div class="col-md-8 chatroom_info">
        <% if @own_notes.present? %>
          <%= form_with url: note_path do |f| %>

            <% @own_notes.each do |note| %>

              <%= check_box_tag 'note[id][]', note.id, checked = false,　id: "orange", :id => "note_#{note.id} " %>

              <div class="btn btn-dark">
                <ul>
                  <li>
                    <div class="note_body">
                      <div class="note_content">
                        <%= note.content %>
                        <% if note.image.present? %>
                          <img src="<%= note.image %>" class="note_image" >
                        <% end %>
                        <%= note.count %>
                          <% if note.count.present? %>
                            <span>個</span>
                          <% end %>
                      </div>


                    </div>
                  </li>
                  <li><button type="button" class="btn btn-secondary js_count_btn" data-toggle="modal" data-target="#count_Modal" value="<%= note.id %>" id="js_count"><i class="fa fa-sort" aria-hidden="true"></i></button></li>
                  <li><button type="button" class="btn btn-secondary js_comment_btn" data-toggle="modal" data-target="#comment_Modal" value="<%= note.id %>" id="js_comment"><i class="fa fa-pencil" aria-hidden="true"></i></button></li>
                </ul>
                <div class="comment">
                  <% note.comments.each do |comment| %>
                    <div class="comment_list">
                      <%= link_to comment.content ,"/comments/#{comment.id}", method: :delete,data:{confirm: "本当に削除しますか?"} %>
                        <span> : </span>
                      <%= comment.user.name %>
                    </div>
                  <% end %>
                </div>
              </div>

              <div class="time"><%= note.created_at.to_s(:datetime) %></div>

            <% end %>

            <%= f.submit '購入しました', class: 'btn btn btn-warning destroy' %>

          <% end %>
        <% else %>
          <p>現在買うものはありません</p>
        <% end %>

        <ul>
          <li><%= link_to "1つ前に戻る",tutorial_index_f_item_path, class:"btn btn-dark" %></li>

          <li><%= link_to "実際に使い始める！",root_path, class:"btn btn-warning" %></li>
        </ul>

        </div>
        <div class="col-md-2">
        </div>
      </div>
    </div>
  </div>
</div>

    <!-- 数量入力用モーダル -->
    <div class="modal fade" id="count_Modal" tabindex="-1" role="dialog" aria-labelledby="count_ModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <%= form_with url: count_path do |f| %>
            <h4 class="modal-title" id="comment_ModalLabel">数量入力欄</h4>
              <div class="modal-body">
                <%= hidden_field_tag :note_id, "", {id: "count_id"} %>
                <%= f.select :count, [['1', 1], ['2', 2], ['3', 3], ['4', 4], ['5', 5], ['6', 6], ['7', 7], ['8', 8], ['9', 9], ['10', 10]],
                    { include_blank: true, selected: 1 }, { id: "user_id", class: "user_class" } %>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">戻る</button>
                <%= f.submit "投稿する", class: "btn btn-primary" %>
              </div>
          <% end %>
        </div>
      </div>
    </div>

    <!-- コメント入力用モーダル -->
    <div class="modal fade" id="comment_Modal" tabindex="-1" role="dialog" aria-labelledby="comment_ModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <%= form_with url: comment_path do |f| %>
            <h4 class="modal-title" id="comment_ModalLabel">コメント入力欄</h4>
            <div class="modal-body">
              <%= hidden_field_tag :note_id, "", {id: "comment_id"} %>
              <%= f.text_area :content, size: "10x5", class: "form-control" %>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal">戻る</button>
              <%= f.submit "投稿する", class: "btn btn-primary" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>

<div class="form_body" id="searches_form"></div>

<script type="text/javascript">
$('.js_count_btn').click(function() {
$('#count_id').val(this.value);
});
$('.js_comment_btn').on('click', function () {
$('#comment_id').val(this.value);
})
</script>