config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'
  }


  # MEMO: devise_scope はあくまで devise が作るルーティングをカスタマイズするためのもののはず
  # つまり、独自のルーティングはこのブロックの中にある必要はない
  # また devise_for も内部で devise_scope を呼び出しているので、devise_scope のみでも良さそう
  devise_scope :user do
    get 'users/index', to: 'users/registrations#index'
    root 'home#index'
    get "/tutorial_top", :to => "home#tutorial_top"
    get "/tutorial_note", :to => "home#tutorial_note"
    get "/tutorial_note_index", :to => "home#tutorial_note_index"
    get "/tutorial_create_f_item", :to => "home#tutorial_create_f_item"
    get "/tutorial_index_f_item", :to => "home#tutorial_index_f_item"
    get "/tutorial_group_create", :to => "home#tutorial_group_create"
    get "/help", :to => "home#help"
    get "user/:id", :to => "users/registrations#detail"
    get "signup", :to => "users/registrations#new"
    get "login", :to => "users/sessions#new"
    get "logout", :to => "users/sessions#destroy"
    post "notes", :to => "notes#create"
    post "note", :to => "notes#destroy"
    post "count", :to => "notes#count"
    post "comment", :to => "comments#create"
    delete "comments/:id",:to => "comments#destroy"
    get "index",:to => "searches#index"
    post "favorite_items_destroy", :to => "favorite_items#destroy"

    resources :groups do
      collection do
        get :request_list
      end
      member do
        get :chatroom
        post :invite
        post :invite_reset
        post :join
      end
    end

    resources :favorite_items, only: [:index,:create,:new]  do
      collection do
        post :post
      end
    end

    resources :reviews
    
  end
end

app/views/layouts/_default.html.erb
<title><%= full_title(yield(:title)) %></title>
<%= csrf_meta_tags %>

<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_footer.html.erb
<nav class="navbar navbar-expand-md navbar-dark bg-dark footer">
  <div class="container-fluid">
    <div class="row footer_item">
      <div class="col-12">
        <div class="row">

        <div class="col-3"><a class= "nav-link" <%= link_to "レビュー一覧",reviews_path %></a></div>
        <div class="col-3"><a class= "nav-link" <%= link_to "レビュー投稿",new_review_path %><span class="footer_title">↑ご協力お願いします！</span></a></div>
        <div class="col-6 contact">
          - 製作者 有吉貴紀 -　<br/>
          - Email takanori20200229@gmail.com - <br/>
            何かあれば 上記emailアドレス宛にご連絡ください
        </div>
  </div>
  </div>
</div>
</nav>
  <div class="f_body">
  <div>

app/views/layouts/_header.html.erb
<nav class="navbar fixed-top navbar-expand-md navbar-dark bg-dark">

  <ul>
  <li><a><img src="/assets/default_group_icon.png" class="app_icon"></a></li>
  <li><p class="logo1">SHOP<span class="logo2">.</span>NOTE</p></li>
  </ul>
  <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#bs-navi" aria-controls="bs-navi" aria-expanded="false" aria-label="Toggle navigation">

    <span class="navbar-toggler-icon"></span>
    <span class="navbar-toggler-icon"></span>
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="bs-navi">
    <ul class="navbar-nav bg-dark ">

  <% if user_signed_in? %>
　　　
      <li class="nav-item"><a class="nav-link" <%= link_to "#{current_user.name}さんがログイン中",edit_user_registration_path(current_user) %></a></li>
      <li class="nav-item"><a class="nav-link" href="/">ホーム</a></li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" onfocus="this.blur();" >ユーザー情報</a>
        <div class="dropdown-menu bg-dark" aria-labelledby="navbarDropdown">
          <a class= "dropdown-item"<%= link_to "ユーザー情報編集",edit_user_registration_path(current_user) %></a>
          <div class="dropdown-divider"></div>
          <a class= "dropdown-item"<%= link_to "ユーザー検索",users_index_path %></a>
          <div class="dropdown-divider"></div>
          <a class= "dropdown-item"<%= link_to "ログアウト",logout_path %></a>
        </div>

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" onfocus="this.blur();" >グループ情報</a>
        <div class="dropdown-menu bg-dark" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" <%= link_to "グループ作成",new_group_path %></a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" <%= link_to "所属グループ一覧",groups_path %></a>

        <a class="dropdown-item" <%= link_to  request_list_groups_path, method: :get do %>
          グループリクエスト一覧
          <% if @request.present? %>
            <i class="fa fa-exclamation-circle"></i>　<%= @request.count %>件</a>
          <% end %>
  <% end %>

            <% if @group_lists.present? %>
              <div class="dropdown-divider"></div>
              <div class="nav_item_title">チャットルーム一覧</div>
                <% @group_lists.each do |group| %>
                  <ul>
                    <li class="nav-link" id="group_list"><a class="group_name"><%= link_to group.group.name,chatroom_group_path(group.group.id) %></a>
                    </li>
                  </ul>
                <% end %>
            <% end %>
        </div>
      <li><a class= "nav-link"<%= link_to "お気に入り商品",new_favorite_item_path %></a></li>
      <li><a class= "nav-link"<%= link_to "ヘルプ",help_path %></a></li>

  <% else %>

    <li class="nav-item"><a class= "nav-link" <%= link_to "ホーム",root_path %></a></li>
    <li class="nav-item"><a class= "nav-link" <%= link_to "新規登録",signup_path %></a><li>
    <li class="nav-item"><a class= "nav-link" <%= link_to "ログイン",new_user_session_path %></a><li>

  <% end %>

　　　</ul>
　　</div>

</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= render 'layouts/default' %>
  </head>

  <body>

    <header>
      <%= render 'layouts/header' %>
    </header>

    <main>
    <%= render 'shared/error_messages' %>
    <%= yield %>
    </main>

    <footer>
    <%= render 'layouts/footer' %>
    </footer>

  </body>
</html>